"""""""""""""""
" vundle begin
"""""""""""""""

set nocompatible              " be iMproved, required
filetype off                  " required

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
" alternatively, pass a path where Vundle should install plugins
"call vundle#begin('~/some/path/here')

" let Vundle manage Vundle, required
Plugin 'https://github.com/VundleVim/Vundle.vim'

" color theme
Plugin 'https://github.com/dracula/vim'
" rainbow color for parentheses
Plugin 'https://github.com/luochen1990/rainbow'
" vertical lines for indentation
Plugin 'https://github.com/Yggdroot/indentLine'
" status line
Plugin 'https://github.com/vim-airline/vim-airline'
" SV highlights
Plugin 'https://github.com/cazador481/vim-systemverilog'

" find file quickly use ctrl-p
Plugin 'https://github.com/ctrlpvim/ctrlp.vim.git'
" align code
" Align around 1st = :EasyAlign =
Plugin 'https://github.com/junegunn/vim-easy-align'
" command code
" \cc  \cu
Plugin 'https://github.com/scrooloose/nerdcommenter'
" increment
" e.g. increase 2 "2<Ctrl-A>"
Plugin 'https://github.com/triglav/vim-visual-increment'
" Preview PlantUML *.puml
" :PlantumlOpen
" :PlantumlStart
Plugin 'https://github.com/tyru/open-browser.vim'
Plugin 'https://github.com/aklt/plantuml-syntax'
Plugin 'https://github.com/weirongxu/plantuml-previewer.vim'

"" The following are examples of different formats supported."
"" Keep Plugin commands between vundle#begin/end."
"" plugin on GitHub repo"
"Plugin 'tpope/vim-fugitive'"
"" plugin from http://vim-scripts.org/vim/scripts.html"
"" Plugin 'L9'"
"" Git plugin not hosted on GitHub"
"Plugin 'git://git.wincent.com/command-t.git'"
"" git repos on your local machine (i.e. when working on your own plugin)"
"Plugin 'file:///home/gmarik/path/to/plugin'"
"" The sparkup vim script is in a subdirectory of this repo called vim."
"" Pass the path to set the runtimepath properly."
"Plugin 'rstacruz/sparkup', {'rtp': 'vim/'}"
"" Install L9 and avoid a Naming conflict if you've already installed a"
"" different version somewhere else."
"" Plugin 'ascenator/L9', {'name': 'newL9'}"


" All of your Plugins must be added before the following line
call vundle#end()            " required
filetype plugin indent on    " required
" To ignore plugin indent changes, instead use:
"filetype plugin on
"
" Brief help
" :PluginList       - lists configured plugins
" :PluginInstall    - installs plugins; append `!` to update or just :PluginUpdate
" :PluginSearch foo - searches for foo; append `!` to refresh local cache
" :PluginClean      - confirms removal of unused plugins; append `!` to auto-approve removal
"
" see :h vundle for more details or wiki for FAQ
" Put your non-Plugin stuff after this line
let g:vundle_default_git_proto = 'git'

"""""""""""""
" vundle end
"""""""""""""

" This must be first, because it changes other options as a side effect.
set nocompatible

"" command
set history=50          " keep 50 lines of command line history
set showcmd             " display incomplete commands

"" display
set ruler               " show the cursor position all the time
set number            " show number lines in front of text
nmap ,nn :set number<CR>
nmap ,,nn :set nonumber<CR>
syntax on

"" tab style : using space to replace tabs
""   while using Make, set noexpandtab
set shiftwidth=4
set softtabstop=4
set expandtab
set smarttab
autocmd FileType make setlocal noexpandtab
autocmd Filetype verilog_systemverilog setlocal shiftwidth=4 softtabstop=4 expandtab smarttab
autocmd Filetype c setlocal shiftwidth=4 softtabstop=4 expandtab smarttab
autocmd Filetype cpp setlocal shiftwidth=4 softtabstop=4 expandtab smarttab
autocmd Filetype javascript setlocal shiftwidth=4 softtabstop=4 expandtab smarttab

set textwidth=0
set wrapmargin=0
set formatoptions-=cro

set fileformat=unix
set encoding=utf-8
set fileencodings=utf-8

"" print
set printfont=YaHei_Consolas_Hybrid:h8
set printheader=%<File:\ %t%=Page:\ %N

" color scheme
" color dracula " has comment out if zsh already use dracula

if (has("gui_running"))
    "" GVim
    set guioptions=amc   "only menu, no toolbar
    colorscheme morning
    set guifont=Menlo:h14
    "set lines=58 columns=238
else
    "" Vim on Termial
    "colorscheme desert
    " colorscheme dracula
    colorscheme default
    set mouse=a
endif

"au BufNewFile,BufReadPre *.asm let b:asmsyntax='masm'
au BufRead,BufNewFile *.upf set filetype=tcl
au BufRead,BufNewFile *.cpf set filetype=tcl
au BufRead,BufNewFile *.sdc set filetype=tcl
au BufRead,BufNewFile *.lib set filetype=tcl
au BufRead,BufNewFile *.nt  set filetype=tcl
au BufRead,BufNewFile *.v   set filetype=verilog_systemverilog
au BufRead,BufNewFile *.vh  set filetype=verilog_systemverilog
au BufRead,BufNewFile *.svi set filetype=verilog_systemverilog
au BufRead,BufNewFile *.svh set filetype=verilog_systemverilog
au BufRead,BufNewFile *.sv  set filetype=verilog_systemverilog
au BufRead,BufNewFile *.bv  set filetype=verilog_systemverilog
au BufRead,BufNewFile *.gv  set filetype=verilog_systemverilog
au BufRead,BufNewFile *.j2sv set filetype=verilog_systemverilog
au BufRead,BufNewFile *.spi set filetype=spice
au BufRead,BufNewFile *.spm set filetype=spice
au BufRead,BufNewFile *.spm028 set filetype=spice
au BufRead,BufNewFile *.md set filetype=markdown
au BufRead,BufNewFile *.mk set filetype=make
au BufRead,BufNewFile *.d set filetype=make
au BufRead,BufNewFile *.j2c set filetype=c
au BufRead,BufNewFile *.j2cc set filetype=cpp

filetype plugin on

"" search
set incsearch           " do incremental searching
set hlsearch
"set ignorecase

"" backup
set backup
set backupdir=~/bak/vim//,/tmp//
set backupskip='*.log'

"" allow backspacing over everything in insert mode
set backspace=indent,eol,start

"" auto indent
set autoindent          " always set autoindenting on

"" auto write before switching between buffers
set noautowriteall

"" match {}[]()
set showmatch
set matchtime=5

""" fold
set foldmethod=marker
set foldmarker={{{,}}}
" autocmd FileType python setlocal foldmethod=syntax
autocmd FileType markdown setlocal foldmethod=marker
autocmd FileType verilog_systemverilog setlocal foldmethod=marker
autocmd FileType cpp setlocal commentstring=\ \/\/\ %s



""" comment
" NERDCommenter
let g:NERDSpaceDelims = 1
let g:NERDDefaultAlign = 'left'
let g:NERDCommentEmptyLines = 1
let g:NERDCustomDelimiters = { 'python': { 'left': '#' } }

"" comment //
vmap ,/  :s/^/\/\/ /g<CR>:nohl<CR>
vmap ,,/ :s/^\/\/ //g<CR>:nohl<CR>
nmap ,/  V:s/^/\/\/ /g<CR>:nohl<CR>
nmap ,,/ V:s/^\/\/ //g<CR>:nohl<CR>
"" comment #
vmap ,3  :s/^/# /g<CR>:nohl<CR>
vmap ,,3 :s/^# //g<CR>:nohl<CR>
nmap ,3  V:s/^/# /g<CR>:nohl<CR>
nmap ,,3 V:s/^# //g<CR>:nohl<CR>
nmap ,j3 :s/^/# jun /g<CR>:nonhl<CR>
vmap ,j3 V:s/^/# jun /g<CR>:nonhl<CR>
"" comment ;
vmap ,;  :s/^/; /g<CR>:nohl<CR>
vmap ,,; :s/^; //g<CR>:nohl<CR>
nmap ,;  V:s/^/; /g<CR>:nohl<CR>
nmap ,,; V:s/^; //g<CR>:nohl<CR>
"" comment *
vmap ,8  :s/^/\* /g<CR>:nohl<CR>
vmap ,,8 :s/^\* //g<CR>:nohl<CR>
nmap ,8  V:s/^/\* /g<CR>:nohl<CR>
nmap ,,8 V:s/^\* //g<CR>:nohl<CR>


""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" key mapping
""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""

" append \ to lines
vmap ,\  :s/$/ \\/<CR>:nohl<CR>
vmap ,,\ :s/ \\$//<CR>

" append " to lines
vmap ,"  :s/^/"/<CR>:'<,'>s/$/"/<CR>:nohl<CR>
vmap ,," :s/^"//<CR>:'<,'>s/"$//<CR>:nohl<CR>

"" up and down arrow
nmap <Up> gkzz
nmap <Down> gjzz

"" find files selected
vmap ,ls y:!ls -l -h <C-R>0<CR>

": grep selectd
vmap ,gg y:grep "<C-R>0" %<CR>
vmap ,ga y:grep "<C-R>0" *.*<CR>
vmap ,gv y:grep "<C-R>0" *.?v<CR>

"" find words
nmap ,ff y:/<CR>0<CR>
vmap ,gg y:grep "<C-R>0" %<CR>

"" find warning or error
nmap ,fe :e<CR>:set ignorecase<CR>/error<CR>
nmap ,fw :e<CR>:set ignorecase<CR>/warning<CR>


"" copy register
" autocmd FocusGained * let @z=@+
" set clipboard=unnamedplus

"" cancel highlight
nmap ,,hh :nohl<CR>

"" ignorecase
nmap ,ii :set ignorecase<CR>
nmap ,,ii :set noignorecase<CR>

"" remove lines with selected keywords
vmap ,rr y:set noignorecase<CR>:%s!^.*<C-R>0.*$\n!!<CR>

"" paste in front of the lines
nmap ,pp V:s!^!<C-R>0!<CR>
vmap ,pp :s!^!<C-R>0!<CR>
"" paste appending to the lines
nmap ,PP V:s!$!<C-R>0!<CR>
vmap ,PP :s!$!<C-R>0!<CR>

"" wrap
nmap ,ww :set wrap<CR>
nmap ,,ww :set nowrap<CR>

"" windows
nmap <Tab> <C-W><C-W>
"""" move to the windows above/under
nmap ,vv  :vsplit<CR><C-W><C-L>:vertical resize +30<CR><C-W><C-H>:set nonumber<CR>:set nowrap<CR><C-W><C-L>
"""" increase window
nmap ,zz  :resize +3<CR>:vertial resize +3<CR>
nmap ,,zz :resize -3<CR>:vertial resize -3<CR>
"""" maximize the window
nmap ,zm  :resize 100<CR>
"""" minimize the window
nmap ,,zm :resize 1<CR>

""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" Abbrev
""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""

"" for commenting
iabbrev //// ///////////////////////////////////////////////////////////////////////////////////////////////////
iabbrev ///= //=============================================================================================
iabbrev ///- //-----------------------------------------------------------------------------------------

iabbrev #### ###################################################################################################
iabbrev #=== #==============================================================================================
iabbrev #--- #------------------------------------------------------------------------------------------

iabbrev """" """""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""

""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
"" for python
""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""

""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" for verilog
""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
inoreabbr aa, always @ (posedge clk or negedge rstn) begin<CR>end<ESC>k$a
inoreabbr af, always_ff @ (posedge clk or negedge rstn) begin<CR>end<ESC>k$a
inoreabbr ac, always_comb begin<CR>end<ESC>k$a
inoreabbr if, if () begin<CR>end else begin<CR>end<ESC>2k$a
inoreabbr case, case ()<CR>endcase<ESC>Odefault:<ESC>k$a
inoreabbr as, assert property (@(posedge clk) disable iff (rstn === '0) ( ))<CR>    else $error("%m: ");<ESC>k$2hi

" quick input
imap <C-B> <ESC>$abegin<CR>end<ESC>O
imap <C-E> <ESC>$aelse begin<CR>end<ESC>O
imap <C-F> <ESC>$abegin<CR>end else begin<CR>end<ESC>kO
imap <C-C> case ()<CR>endcase<ESC>k$i

" verilog
let g:verilog_disable_indent_lst = "module,conditional,eos"

""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" plugins
""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""

"" nerd tree
nmap ,nt :NERDTreeToggle<CR>
let g:NERDTreeWinSize = 20

nmap <C-H> :bp<CR>
nmap <C-J> :bp<CR>
nmap <C-K> :bn<CR>
nmap <C-L> :bn<CR>

"" python syntax
let python_highlight_all = 1

if &diff
    set nonu
    set diffopt+=iwhite
endif

let g:rainbow_active = 1
runtime macros/matchit.vim
runtime! macros/matchit.vim
if exists('loaded_matchit')
  let b:match_ignorecase=0
  let b:match_words=
    \ '\<begin\>:\<end\>,' .
    \ '\<if\>:\<else\>,' .
    \ '\<module\>:\<endmodule\>,' .
    \ '\<class\>:\<endclass\>,' .
    \ '\<program\>:\<endprogram\>,' .
    \ '\<clocking\>:\<endclocking\>,' .
    \ '\<property\>:\<endproperty\>,' .
    \ '\<sequence\>:\<endsequence\>,' .
    \ '\<package\>:\<endpackage\>,' .
    \ '\<covergroup\>:\<endgroup\>,' .
    \ '\<primitive\>:\<endprimitive\>,' .
    \ '\<specify\>:\<endspecify\>,' .
    \ '\<generate\>:\<endgenerate\>,' .
    \ '\<interface\>:\<endinterface\>,' .
    \ '\<function\>:\<endfunction\>,' .
    \ '\<task\>:\<endtask\>,' .
    \ '\<case\>\|\<casex\>\|\<casez\>:\<endcase\>,' .
    \ '\<fork\>:\<join\>\|\<join_any\>\|\<join_none\>,' .
    \ '`ifdef\>:`else\>:`endif\>,'
endif

let g:indentLine_concealcursor = "nv"
"let g:indentLine_setConceal = 0

"" autocomplete
highlight Pmenu ctermfg=black ctermbg=grey gui=bold
highlight PmenuSel cterm=bold ctermfg=blue ctermbg=white gui=bold
set completeopt=menu,menuone,longest    " Use the popup menu by default; only insert the longest common text of the completion matches; don't automatically show extra information in the preview window.

let g:SuperTabDefaultCompletionType = 'context'

"" airline
let g:airline#extensions#tabline#enabled = 1
let g:airline#extensions#tabline#buffer_idx_mode = 1
let g:airline#extensions#tabline#fnametruncate = 0
let g:airline#extensions#tabline#formatter = 'unique_tail'
let g:airline#extensions#tabline#fnamemod = ':t'
nmap <leader>1 <Plug>AirlineSelectTab1
nmap <leader>2 <Plug>AirlineSelectTab2
nmap <leader>3 <Plug>AirlineSelectTab3
nmap <leader>4 <Plug>AirlineSelectTab4
nmap <leader>5 <Plug>AirlineSelectTab5
nmap <leader>6 <Plug>AirlineSelectTab6
nmap <leader>7 <Plug>AirlineSelectTab7
nmap <leader>8 <Plug>AirlineSelectTab8
nmap <leader>9 <Plug>AirlineSelectTab9
nmap <leader>- <Plug>AirlineSelectPrevTab
nmap <leader>+ <Plug>AirlineSelectNextTab

