FROM ubuntu:20.04

ENV DEBIAN_FRONTEND noninteractive

RUN apt-get update \
  && apt-get install -y \
    build-essential \
    cmake \
    wget \
    git \
    zsh \
    less \
    vim \
    python3 \
  && apt-get clean

